### ISSUE TITLE
There was a COM failure 0x80042308 - .\HoboCopy.cpp (351)

### ISSUE THREAD

**Issue by KMcCullough1234** [candera/hobocopy#49]
I am attempting to set up a script to run nightly backups from other servers to my backup server. I have created a backup script to run a full backup that has a few lines that look like this: hobocopy /full /skipdenied /y /r \(Server Name)(Shared Folder) F:(Backup Folder)(Server Folder). When I run this command while testing I get the error There was a COM failure 0x80042308 - .\HoboCopy.cpp (351). I can copy files from my backup server to a network share but not the other way. I have checked to make sure the VSS and MSSCP services are set to manual on my backup server and other servers. Our old backup server uses robocopy and works correctly but when trying to rewrite the scripts using hobocopy syntax I run into this issue.

**Comment by candera** [comment]
VSS does not support shadowing a remote drive: the source must be a local volume.
